apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-depl
spec:
  replicas: 2
  selector: # defines which pod the deployment manages
    matchLabels:
      app: control # defining what label of pod to search for
  template:
    metadata:
      labels:
        app: control # defining what labels the pod has
    spec:
      containers:
        - name: control
          image: baelthebard42/control:latest
          env:
            - name: JWT_SECRET # environment variable name inside container 
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-hulaak # this refers to kubernetes secrets object name
                  key: JWT_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets-hulaak
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets-hulaak
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets-hulaak
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
          imagePullPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: control-srv
spec:
  type: NodePort
  selector:
    app: control
  ports:
    - port: 80 # for this service
      targetPort: 8080 # for this container
      nodePort: 30008 # for this node (physical/vm)




